apiVersion: v1
kind: Secret
metadata:
  name: jenkins-admin-secret
  namespace: jenkins
  labels:
    app: jenkins
type: Opaque
stringData:
  JENKINS_ADMIN_ID: jenkins-user
  JENKINS_ADMIN_PASSWORD: Viettel123
